### ISSUE TITLE
A3.3 - S2 (Métricas)

### ISSUE THREAD

**Issue by LuisUsrDev** [gii-is-psg2/PSG2-2021-G5-54#33]
As a group, create a technical report (in Spanish) entitled “Métricas de Proceso Ágil y Recursos”. This document must contain at least the following items:

   - For Sprint S2:
       * BurnDown chart,
       * total history points delivered,
       * percentage of history points delivered.

**Comment by fernando-hidalgo** [comment]
Muy bien explicado, impecable
